CREATE TABLE IF NOT EXISTS cash_bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('cash', 'bank')),
    account_number TEXT,
    bank_name TEXT,
    opening_balance NUMERIC(15, 2) DEFAULT 0,
    opening_balance_date DATE,
    current_balance NUMERIC(15, 2) DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL UNIQUE,
    unit TEXT DEFAULT 'KG',
    current_stock NUMERIC(15, 3) DEFAULT 0,
    avg_cost NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    opening_balance NUMERIC(15, 2) DEFAULT 0,
    current_balance NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    opening_balance NUMERIC(15, 2) DEFAULT 0,
    current_balance NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id TEXT UNIQUE NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    qty_kg NUMERIC(15, 3) NOT NULL,
    rate NUMERIC(15, 2) NOT NULL,
    total NUMERIC(15, 2) NOT NULL,
    freight_charges NUMERIC(15, 2) DEFAULT 0,
    amount_paid NUMERIC(15, 2) DEFAULT 0,
    payment_method TEXT CHECK(payment_method IN ('cash', 'bank', 'none')),
    date DATE NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'draft' CHECK(status IN ('draft', 'approved', 'voided')),
    approved_at TIMESTAMPTZ,
    approved_by BIGINT,
    voided INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id TEXT UNIQUE NOT NULL,
    vendor_id BIGINT NOT NULL REFERENCES vendors(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    qty_kg NUMERIC(15, 3) NOT NULL,
    rate NUMERIC(15, 2) NOT NULL,
    total NUMERIC(15, 2) NOT NULL,
    freight_charges NUMERIC(15, 2) DEFAULT 0,
    other_charges NUMERIC(15, 2) DEFAULT 0,
    grand_total NUMERIC(15, 2) NOT NULL,
    amount_paid NUMERIC(15, 2) DEFAULT 0,
    payment_method TEXT CHECK(payment_method IN ('cash', 'bank', 'none')),
    bank_account_id BIGINT REFERENCES cash_bank_accounts(id),
    date DATE NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'draft' CHECK(status IN ('draft', 'approved', 'voided')),
    approved_at TIMESTAMPTZ,
    approved_by BIGINT,
    is_direct_delivery INTEGER DEFAULT 0,
    voided INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id TEXT UNIQUE NOT NULL,
    party_type TEXT NOT NULL CHECK(party_type IN ('customer', 'vendor')),
    party_id BIGINT NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    method TEXT NOT NULL CHECK(method IN ('cash', 'bank', 'cheque')),
    bank_account_id BIGINT REFERENCES cash_bank_accounts(id),
    cheque_number TEXT,
    cheque_date DATE,
    direction TEXT NOT NULL CHECK(direction IN ('in', 'out')),
    date DATE NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'draft' CHECK(status IN ('draft', 'approved', 'voided')),
    approved_at TIMESTAMPTZ,
    approved_by BIGINT,
    voided INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    vendor_id BIGINT NOT NULL REFERENCES vendors(id),
    amount NUMERIC(15, 2) NOT NULL,
    date DATE NOT NULL,
    notes TEXT,
    voided INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_type TEXT NOT NULL CHECK(ref_type IN ('sale', 'purchase', 'payment', 'settlement', 'bank_transaction')),
    ref_id BIGINT NOT NULL,
    party_type TEXT CHECK(party_type IN ('customer', 'vendor', 'account')),
    party_id BIGINT,
    account_type TEXT CHECK(account_type IN ('receivable', 'payable', 'cash', 'bank', 'stock', 'revenue', 'cogs', 'freight', 'commission')),
    debit NUMERIC(15, 2) DEFAULT 0,
    credit NUMERIC(15, 2) DEFAULT 0,
    date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bank_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id TEXT UNIQUE NOT NULL,
    transaction_type TEXT NOT NULL CHECK(transaction_type IN ('deposit', 'withdrawal', 'transfer')),
    from_account_id BIGINT REFERENCES cash_bank_accounts(id),
    to_account_id BIGINT REFERENCES cash_bank_accounts(id),
    amount NUMERIC(15, 2) NOT NULL,
    date DATE NOT NULL,
    reference TEXT,
    notes TEXT,
    status TEXT DEFAULT 'draft' CHECK(status IN ('draft', 'approved', 'voided')),
    approved_at TIMESTAMPTZ,
    approved_by BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS direct_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id TEXT UNIQUE NOT NULL,
    purchase_id BIGINT NOT NULL REFERENCES purchases(id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    product_cost NUMERIC(15, 2) NOT NULL,
    freight_charges NUMERIC(15, 2) NOT NULL,
    total_received NUMERIC(15, 2) NOT NULL,
    commission_amount NUMERIC(15, 2) DEFAULT 0,
    amount_to_vendor NUMERIC(15, 2) NOT NULL,
    date DATE NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'draft' CHECK(status IN ('draft', 'approved', 'voided')),
    approved_at TIMESTAMPTZ,
    approved_by BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT DEFAULT 'staff' CHECK(role IN ('owner', 'staff')),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sales_customer ON sales(customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_product ON sales(product_id);
CREATE INDEX IF NOT EXISTS idx_sales_date ON sales(date);
CREATE INDEX IF NOT EXISTS idx_purchases_vendor ON purchases(vendor_id);
CREATE INDEX IF NOT EXISTS idx_purchases_product ON purchases(product_id);
CREATE INDEX IF NOT EXISTS idx_purchases_date ON purchases(date);
CREATE INDEX IF NOT EXISTS idx_payments_party ON payments(party_type, party_id);
CREATE INDEX IF NOT EXISTS idx_settlements_customer ON settlements(customer_id);
CREATE INDEX IF NOT EXISTS idx_settlements_vendor ON settlements(vendor_id);
CREATE INDEX IF NOT EXISTS idx_ledger_ref ON ledger_entries(ref_type, ref_id);
CREATE INDEX IF NOT EXISTS idx_ledger_date ON ledger_entries(date);